owner: daotrunghieu
repo: upptime
user-agent: github; upptime

status-website:
  # cname: status.daotrunghieu.com
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle:
  introMessage:

var:
  - &site01 $SITE01
  - &site02 $SITE02

sites:
  - name: HOME
    url: $SITE01
    assignees:
      - daotrunghieu
    maxResponseTime: 2000

  - name: grafana
    url: *site01
    assignees:
      - daotrunghieu
    maxResponseTime: 2000

  - name: kibana
    url: kibana.daotrunghieu.com
    assignees:
      - daotrunghieu
    maxResponseTime: 2000

  - name: jenkins
    url: ci.daotrunghieu.com
    assignees:
      - daotrunghieu
    maxResponseTime: 2000

  - name: wiki
    url: wiki.daotrunghieu.com
    assignees:
      - daotrunghieu
    maxResponseTime: 2000

  - name: blog
    url: blog.daotrunghieu.com
    assignees:
      - daotrunghieu
    maxResponseTime: 2000